package_name: mci_model

training_data_file: train.csv
test_data_file: test.csv

pipeline_name: mci_model
pipeline_save_file: mci_model_output_v

column_to_drop: event_unique_id
targets:
  - Lat
  - Long

features:
  - occurrencehour
  - Pub_Id
  - Park_Id
  - PS_Id
  - premises_type
  - occurrencemonth
  - occurrencedayofweek
  - MCI
  - Neighbourhood
  - occurrenceday
  - occurrencedayofyear

test_size: 0.2

random_state: 0

holidays:
  - 1
  - 46
  - 92
  - 144
  - 182
  - 249
  - 284
  - 359
  - 360
    
levels:
  high:
    - 0
    - 12
    - 18
    - 21
    - 20
    - 22
    - 19
    - 23
    - 17
    - 15
  med: 
    - 16
    - 14
    - 1
    - 2
    - 13
    - 11
    - 10
    - 9
    - 3
    - 8
  low: 
    - 4
    - 7
    - 5
    - 6

seasons:
  winter: 
    - 354
    - 77 
  spring: 
    - 78
    - 170
  summer: 
    - 171 
    - 264
  fall: 
    - 265
    - 353