version: 2

defaults: &defaults
  docker:
    - image: circleci/python:3.9.5
  working_directory: ~/project

prepare_venv: &prepare_venv
  run:
    name: Create venv
    command: |
      python3 -m venv venv
      source venv/bin/activate
      pip install --upgrade pip

prepare_tox: &prepare_tox
  run:
    name: Install tox
    command: |
      sudo pip install --upgrade pip
      pip install --user tox

prepare_twine: &prepare_twine
  run:
    name: Install twine
    command: |
      sudo pip install --upgrade pip
      pip install --user twine


jobs:
  model_test_and_upload_test:
    <<: *defaults
    working working_directory: ~/project/model_package
    steps:
      - checkout:
          path: ~/project
      - *prepare_tox
      - *prepare_twine
      - run:
          name: test model package
          command: |
            tox
      - run:
          name: upload to testpypi
          command: |
            tox -e publish_test_model

  test_app:
    <<: *defaults
    working_directory: ~/project/mci-api
    steps:
      - checkout:
          path: ~/project
      - *prepare_tox
      - run:
          name: testing mci app
          command: 
            # runs test by posting payload to api
            |
            tox

  deploy_app_to_heroku:
    <<: *defaults
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Deploy to Heroku
          command: |
            git push /mci-api https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

  test_and_upload_regression_model:
    <<: *defaults
    working_directory: ~/project/model_package
    steps:
      - checkout:
          path: ~/project
      - *prepare_tox
      - *prepare_twine
      - run:
          name: Test the model
          command: |
            tox
      - run:
          name: Publish model to PyPI
          command: |
            tox -e publish_model

  biuld_push_release_heroku:
    <<: *defaults
    working_directory: ~/project/
    steps:
      - setup_remote_docker:
          version: 20.10.6
      - checkout:
          path: ~/project
      - run:
          name: Longin to Heroku and build image
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            make build
      - run:
          name: Push image to Heroku
          command: |
            make push
      - run:
          name: Release to Heroku
          command: |
            make release

 
workflows:
  version: 2
  # code_deploy_heroku:
  #   jobs:
  #     - model_test_and_upload_test
  #     - test_app:
  #         requires:
  #           - model_test_and_upload_test
  #         filters:
  #           branches:
  #             only:
  #               - master
  #     - deploy_app_to_heroku:
  #         requires:
  #           - test_app
  #         filters:
  #           branches:
  #             only:
  #               - master
  #     - test_and_upload_regression_model
  #        # <<: *tags_only
  container_deploy_heroku:
    jobs:
      - biuld_push_release_heroku:
          filters:
            branches:
              only:
                - master