apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    object: pg_pod
data:
  # these are normally defined under secretKeyRef, but are maintained as public
  # for users to test out the service
  POSTGRES_DB: mci-app-db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password