apiVersion: v1
kind: Service
metadata:
  name: worker-app-service
spec:
  type: NodePort 	# default
  ports:
    - nodePort: 30005	# server/localhost port exposed
      port: 8001 	# service port exposed
      targetPort: 8001	# exposed container port
  selector:
    object: mci_worker_pod